### PR TITLE
Improve specification text referring to DOM Futures (Improves #29)

### PR DESCRIPTION
**Pull request by cdumez**
Indicate that the remaining steps should be run asynchronously when
returning a future.

### CODE REVIEW

**Comment by martap** [comment]
LGTM

**Comment by marcoscaceres** [comment]
Don't forget that Futures are not called Promises :)

**Comment by cdumez** [comment]
are _not_ or are _now_ ? :)

**Comment by marcoscaceres** [comment]
Ah crap! the worst typo mistake evar! :dancer:

**Pull request merged**
